version: '3'

networks:
  spring-cloud-net:
    driver: bridge

services:
  zipkin-server:
    container_name: 'zipkin-server'
    networks:
      - spring-cloud-net
    build:
      context: .
      dockerfile: /zipkin/Dockerfile
    ports:
      - '9411:9411'

  eureka-discovery-server:
    container_name: 'eureka-discovery-server'
    networks:
      - spring-cloud-net
    build:
      context: .
      dockerfile: /eureka-discovery-server/Dockerfile
    ports:
      - '8761:8761'
    environment:
      - ZIPKIN_URI=http://zipkin-server:9411
#      - EUREKA_URI=http://eureka-discovery-server:8761
    depends_on:
      - kafka-server

  configuration-server:
    container_name: 'configuration-server'
    networks:
      - spring-cloud-net
    build:
      context: .
      dockerfile: /configuration-server/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - GIT_URI=https://github.com/MrKami-Kirill/config-repo
#      - EUREKA_URI=http://eureka-discovery-server:8761
      - KAFKA_ADDR=http://kafka-server:9092
    depends_on:
      - eureka-discovery-server

  proxy-module:
    container_name: 'proxy-module'
    networks:
      - spring-cloud-net
    build:
      context: .
      dockerfile: /proxy-module/Dockerfile
    ports:
      - '8081:8081'
    environment:
      - CONFIG_URI=http://configuration-server:8080
      - ZIPKIN_URI=http://zipkin-server:9411
#      - EUREKA_URI=http://eureka-discovery-server:8761
      - KAFKA_ADDR=http://kafka-server:9092
    restart: always
    depends_on:
      - configuration-server
      - client-service

  client-service:
    container_name: 'client-service'
    networks:
      - spring-cloud-net
    hostname: 'client-service'
    build:
      context: .
      dockerfile: /client-service/Dockerfile
    ports:
      - '8082:8082'
    environment:
      - CONFIG_URI=http://configuration-server:8080
      - ZIPKIN_URI=http://zipkin-server:9411
#      - EUREKA_URI=http://eureka-discovery-server:8761
      - KAFKA_ADDR=http://kafka-server:9092
    depends_on:
      - configuration-server

  zookeeper-server:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    networks:
      - spring-cloud-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: bitnami/kafka:latest
    container_name: kafka-server
    networks:
      - spring-cloud-net
    ports:
      - '9092:9092'
    volumes:
      - ~/.docker-conf/kafka/local/:/usr/local/
    environment:
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
      - zipkin-server