###
POST http://spring-cloud.proxy-module.com/actuator/busrefresh

###
GET https://spring-cloud.proxy-module.com/proxy-module/getClients
Content-Type: application/json

###
GET https://spring-cloud.proxy-module.com/proxy-module/getClientById/1
Content-Type: application/json

###
GET https://spring-cloud.proxy-module.com/proxy-module/getClientContacts/1
Content-Type: application/json

###
POST https://spring-cloud.proxy-module.com/proxy-module/addClient
Content-Type: application/json

{
  "surName": "Иванов2",
  "firstName": "Иван2",
  "middleName": "Иванович2",
  "birthDay": "1994-09-04"
}

###
PUT https://spring-cloud.proxy-module.com/proxy-module/changeClient/1
Content-Type: application/json

{
  "surName": "Петров",
  "firstName": "Петр",
  "middleName": "Петрович",
  "birthDay": "1994-09-05"
}

###
POST https://spring-cloud.proxy-module.com/proxy-module/addContactToClient/1
Content-Type: application/json

{
  "value": "+79999999991",
  "type": "MOBILE"
}

###
DELETE https://spring-cloud.proxy-module.com/proxy-module/deleteClient/1
Content-Type: application/json

###
DELETE https://spring-cloud.proxy-module.com/proxy-module/deleteClientContact/1/1
Content-Type: application/json