###
POST http://localhost:8081/actuator/busrefresh

###
GET http://localhost:8081/proxy-module/getClients
Content-Type: application/json

###
GET http://localhost:8081/proxy-module/getClientById/2
Content-Type: application/json