apiVersion: v1
kind: Service
metadata:
  name: configuration-server-service
  namespace: spring-cloud
  labels:
    app: configuration-server
spec:
  ports:
    - port: 8079
  selector:
    app: configuration-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-server-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: configuration-server
    spec:
      containers:
        - name: configuration-server-container
          image: configuration-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8079
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: 'https://github.com/MrKami-Kirill/config-repo'
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: 'http://kafka-server-service:9092'
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: 'http://eureka-discovery-server-peer-1-service:8761/eureka/,
              http://eureka-discovery-server-peer-2-service:8762/eureka/,
              http://eureka-discovery-server-peer-3-service:8763/eureka/'
  selector:
    matchLabels:
      app: configuration-server
