server:
  port: 8888

logging:
  level:
    ROOT: INFO

#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,env,prometheus

spring:
  application:
    name: configuration-server
  banner:
    location: banner
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrKami-Kirill/config-repo
          default-label: master
          clone-on-start: true
          search-paths: '{application}'
        encrypt:
          enabled: true
        default-profile: default
  security:
    user:
      name: root
      password: root

encrypt:
  key: mySecretKey