server:
  port: 8888

logging:
  level:
    ROOT: ERROR

#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,env,prometheus

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrKami-Kirill/config-repo
          default-label: main
          search-paths: '{application}'
        encrypt:
          enabled: false
        default-profile: default