server:
  port: 8891

#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,env,prometheus

spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 100
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka
      register-with-eureka: true
      fetch-registry: true
      eviction-interval-timer-in-ms: 15000
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
