apiVersion: v1
kind: Service
metadata:
  name: client-service-service
  namespace: spring-cloud
  labels:
    app: client-service
spec:
  ports:
    - port: 8082
  selector:
    app: client-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service-container
          image: client-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_URI
              value: 'http://configuration-server-service:8079'
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: 'http://kafka-server-service:9092'
            - name: SPRING_ZIPKIN_BASE_URL
              value: 'http://zipkin-server-service:9411'
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: 'http://eureka-discovery-server-peer-1-service:8761/eureka/,
              http://eureka-discovery-server-peer-2-service:8762/eureka/,
              http://eureka-discovery-server-peer-3-service:8763/eureka/'
  selector:
    matchLabels:
      app: client-service
