apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-server-peer-1-service
  namespace: spring-cloud
  labels:
    app: eureka-discovery-server-peer-1
spec:
  ports:
    - port: 8761
  selector:
    app: eureka-discovery-server-peer-1
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-server-peer-2-service
  namespace: spring-cloud
  labels:
    app: eureka-discovery-server-peer-2
spec:
  ports:
    - port: 8762
  selector:
    app: eureka-discovery-server-peer-2
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-discovery-server-peer-3-service
  namespace: spring-cloud
  labels:
    app: eureka-discovery-server-peer-3
spec:
  ports:
    - port: 8763
  selector:
    app: eureka-discovery-server-peer-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-server-peer-1-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-discovery-server-peer-1
    spec:
      containers:
        - name: eureka-discovery-server-peer-1-container
          image: eureka-discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'peer-1'
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: 'http://eureka-discovery-server-peer-2-service:8762/eureka/,http://eureka-discovery-server-peer-3-service:8763/eureka/'
  selector:
    matchLabels:
      app: eureka-discovery-server-peer-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-server-peer-2-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-discovery-server-peer-2
    spec:
      containers:
        - name: eureka-discovery-server-peer-2-container
          image: eureka-discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8762
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'peer-2'
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: 'http://eureka-discovery-server-peer-1-service:8761/eureka/,
              http://eureka-discovery-server-peer-3-service:8763/eureka/'
  selector:
    matchLabels:
      app: eureka-discovery-server-peer-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-discovery-server-peer-3-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-discovery-server-peer-3
    spec:
      containers:
        - name: eureka-discovery-server-peer-3-container
          image: eureka-discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8763
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'peer-3'
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
              value: 'http://eureka-discovery-server-peer-1-service:8761/eureka/,
              http://eureka-discovery-server-peer-2-service:8762/eureka/'
  selector:
    matchLabels:
      app: eureka-discovery-server-peer-3
