server:
  port: 8761

logging:
  level:
    ROOT: INFO

#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
    logfile:
      enabled: true
    prometheus:
      enabled: true
  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      mode: "full"

spring:
  application:
    name: eureka-discovery-server
  banner:
    location: banner
  zipkin:
    base-url: ${ZIPKIN_URI:http://zipkin-server:9411/}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-discovery-server:8761/eureka}
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    registry-sync-retries: 3
    max-threads-for-peer-replication: 0
    enable-self-preservation: false