server:
  port: 8889

logging:
  level:
    ROOT: INFO

#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,env,prometheus

spring:
  application:
    name: eureka-discovery-server
  banner:
    location: banner

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    registry-sync-retries: 3
    max-threads-for-peer-replication: 0
    enable-self-preservation: false