server:
  port: 8890

logging:
  level:
    ROOT: INFO
    #feign logging
    spring.cloud.feign.ClientServiceProxy: INFO

#actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,env,prometheus,info

spring:
  application:
    name: proxy-module
  banner:
    location: banner
  cloud:
    config:
      uri: ${CONFIG_URI:http://localhost:8888}
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:http://localhost:9092}
  config:
    import: optional:configserver:${CONFIG_URI:http://localhost:8888}
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  sleuth:
    sampler:
      probability: 100
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411/}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8889/eureka}
      register-with-eureka: true
      fetch-registry: true
      eviction-interval-timer-in-ms: 15000
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true

encrypt:
  key: mySecretKey

#feign
reactive:
  feign:
    client:
      config:
        client-service:
          options:
            readTimeoutMillis: 2000
            writeTimeoutMillis: 2000
            responseTimeoutMillis: 2000

