CREATE SCHEMA IF NOT EXISTS db_client_data AUTHORIZATION spring_cloud_user;

CREATE TABLE IF NOT EXISTS db_client_data.tclient
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sur_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    middle_name character varying(100) COLLATE pg_catalog."default",
    birth_day date NOT NULL,
    CONSTRAINT pkttclient_id PRIMARY KEY (id)
    );

CREATE TYPE IF NOT EXISTS db_client_data.contact_type AS ENUM ('EMAIL', 'MOBILE', 'LANDLINE');

CREATE TABLE IF NOT EXISTS db_client_data.tcontact
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    value character varying(100) COLLATE pg_catalog."default" NOT NULL,
    contact_type db_client_data.contact_type NOT NULL,
    tclient_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT pktcontact_id PRIMARY KEY (id),
    CONSTRAINT fktclient_tcontact_id FOREIGN KEY (tclient_id)
    REFERENCES db_client_data.tclient (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    );