apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource-backend
  namespace: spring-cloud
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: spring-cloud.zipkin-server.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zipkin-server-service
                port:
                  number: 9411
    - host: spring-cloud.kafka-ui.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-ui-service
                port:
                  number: 8080
    - host: spring-cloud.eureka-discovery-server.com
      http:
        paths:
          - path: /peer-1
            pathType: Prefix
            backend:
              service:
                name: eureka-discovery-server-peer-1-service
                port:
                  number: 8761
          - path: /peer-2
            pathType: Prefix
            backend:
              service:
                name: eureka-discovery-server-peer-2-service
                port:
                  number: 8762
          - path: /peer-3
            pathType: Prefix
            backend:
              service:
                name: eureka-discovery-server-peer-3-service
                port:
                  number: 8763
    - host: spring-cloud.hystrix-dashboard.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hystrix-dashboard-service
                port:
                  number: 8076
    - host: spring-cloud.configuration-server.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: configuration-server-service
                port:
                  number: 8079
    - host: spring-cloud.proxy-module.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-module-service
                port:
                  number: 8081