apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: spring-cloud
spec:
  ports:
    - port: 8080
  selector:
    app: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui-container
          image: provectuslabs/kafka-ui:latest
          env:
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: 'kafka-server-1-service:9092,kafka-server-2-service:9092,kafka-server-3-service:9092'
            - name: KAFKA_CLUSTERS_0_NAME
              value: 'kraft'
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: kafka-ui
