apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-server-config
  namespace: spring-cloud
  labels:
    app: pg-server
data:
  POSTGRES_USER: spring_cloud_user
  POSTGRES_PASSWORD: r53x46MXEz&H
  POSTGRES_DB: db_client_data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-server-pv-volume
  labels:
    type: local
    app: pg-server
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-server-pv-claim
  labels:
    app: pg-server
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg-server-service
  namespace: spring-cloud
  labels:
    app: pg-server
spec:
  type: NodePort
  ports:
    - name: '5432'
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 30360
  selector:
    app: pg-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-server-deployment
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pg-server
    spec:
      containers:
        - name: pg-server-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pg-server-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: pg-server-pv-claim
  selector:
    matchLabels:
      app: pg-server