GET http://localhost:8891/client-service/clients
Content-Type: application/json

###
GET http://localhost:8891/client-service/clients/2
Content-Type: application/json

###
GET http://localhost:8891/client-service/clients/2/contacts
Content-Type: application/json

###
POST http://localhost:8891/client-service/clients
Content-Type: application/json

{
  "surName": "Иванов",
  "firstName": "Иван",
  "middleName": "Иванович",
  "birthDay": "1994-09-05"
}

###
PUT http://localhost:8891/client-service/clients/2
Content-Type: application/json

{
  "surName": "Петров",
  "firstName": "Петр",
  "middleName": "Петрович",
  "birthDay": "1994-09-05"
}

###
POST http://localhost:8891/client-service/clients/2/contacts
Content-Type: application/json

{
  "value": "test@test.com",
  "type": "EMAIL"
}

###
DELETE http://localhost:8891/client-service/clients/4/
Content-Type: application/json

###
DELETE http://localhost:8891/client-service/clients/2/contacts/2
Content-Type: application/json